image: python:latest

stages:
  - format
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: "cxp_test"
  POSTGRES_USER: "cxp"
  POSTGRES_PASSWORD: "token.01"
  DATABASE_URI: "postgresql+psycopg2://cxp:token.01@cxp_db:5432/cxp_test"
  FIREBASE_TOKEN: "1//01oOxnx8H1x1bCgYIARAAGAESNwF-L9IrDYa8EKEGhP55_lSx5MzPI-76952cMi9esR06R45VTkqzwkYhx5x2ydqBArg1UzfqH54"
  FIREBASE_AUTH_EMULATOR_HOST: "emulator:9099"
  FIREBASE_PORT: "9099"
  FIREBASE_PROJECT: "conxperto-admin"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - .venv/

services:
  - name: postgres:13-alpine
    alias: cxp_db
  - name: frfernandezdev/firebase-emulators:latest
    alias: emulator

format:
  stage: format
  before_script:
    - pip install black
    - pip install flake8
  script:
    - black --config=.black .
    - flake8 .

test:
  stage: test
  needs:
    - format
  only:
    - main
    - develop
    - /^feature-[0-9]\d*(\.[0-9]\d*)*$/
    - /^hotfix-[0-9]\d*(\.[0-9]\d*)*$/
    - /^staging-[0-9]\d*(\.[0-9]\d*)*$/
    - /^release-[0-9]\d*(\.[0-9]\d*)*$/
    - merge_requests
  before_script:
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest tests/test_cli.py

staging:
  stage: deploy
  needs:
    - test
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY

prod:
  stage: deploy
  needs:
    - test
  only:
    - tags
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api_key=$HEROKU_API_KEY
