# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: '^app/'
fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports   
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: ['--autofix']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: name-tests-test
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        -  ./app/
