# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
    -   id: gitlint
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        name: black
        exclude: ^migrations/
        args:
        -   --config=.black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^migrations/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^migrations/
    -   id: end-of-file-fixer
        exclude: ^migrations/
    -   id: pretty-format-json
        args: ['--autofix']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: ^migrations/
    -   id: check-json
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^migrations/
        name: flake8
