version: "3"

services:
    db:
      container_name: cxp_db
      image: postgres:13-alpine
      env_file: ./docker/db/db.conf
      ports:
        - "5432:5432"
      volumes:
        - ./docker/db/pg-init-scripts:/docker-entrypoint-initdb.d
    emulator_admin:
      container_name: cxp_emulator_admin
      image: frfernandezdev/firebase-emulators:latest
      ports:
        - "9000:9000"
        - "9099:9099"
      environment:
        - FIREBASE_PROJECT=conexperto-admin
        - FIREBASE_TOKEN=1//01oOxnx8H1x1bCgYIARAAGAESNwF-L9IrDYa8EKEGhP55_lSx5MzPI-76952cMi9esR06R45VTkqzwkYhx5x2ydqBArg1UzfqH54
        - FIREBASE_UI_ENABLED=true
    emulator_web:
      container_name: cxp_emulator_web
      image: frfernandezdev/firebase-emulators:latest
      ports:
        - "9001:9001"
        - "9098:9098"
      environment:
        - FIREBASE_PROJECT=conexperto-6b5e7
        - FIREBASE_TOKEN=1//01oOxnx8H1x1bCgYIARAAGAESNwF-L9IrDYa8EKEGhP55_lSx5MzPI-76952cMi9esR06R45VTkqzwkYhx5x2ydqBArg1UzfqH54
        - FIREBASE_UI_ENABLED=true
        - FIREBASE_AUTH_PORT=9098
        - FIREBASE_UI_PORT=9001
    api:
      build:
        context: .
        dockerfile: ./docker/api/Dockerfile
      env_file: ./docker/api/api.conf
      volumes:
        - ./:/srv/app
      ports:
        - "5000:5000"
      depends_on:
        - db
        - emulator_admin
        - emulator_web
    test:
      build:
        context: .
        dockerfile: ./docker/test/Dockerfile
      env_file: ./docker/test/test.conf
      volumes:
        - ./:/srv/test
      depends_on:
        - db
        - emulator_admin
        - emulator_web

networks:
  default:
    driver: bridge
