version: "3"

services: 
    db: 
        image: postgres:13-alpine
        env_file: ./docker/db/db.conf
        ports: 
            - "5432:5432"
    api: 
        build: 
            context: .
            dockerfile: ./docker/api/Dockerfile
        env_file: ./docker/api/api.conf
        volumes: 
            - ./app:/srv/app
        ports:
            - "5000:3000"
        depends_on:
            - db
        restart: always
