version: "3"

services:
    db:
      container_name: cxp_db
      image: postgres:13-alpine
      env_file: ./docker/db/db.conf
      ports:
        - "5432:5432"
      volumes:
        - ./docker/db/pg-init-scripts:/docker-entrypoint-initdb.d
    emulator_admin:
      container_name: cxp_emulator_admin
      image: frfernandezdev/firebase-emulators:latest
      environment:
        - FIREBASE_UI_ENABLED=true
        - FIREBASE_PROJECT=cxp-dev-admin
      ports:
        - "9000:9000"
        - "9099:9099"
    emulator_web:
      container_name: cxp_emulator_web
      image: frfernandezdev/firebase-emulators:latest
      environment:
        - FIREBASE_UI_ENABLED=true
        - FIREBASE_PROJECT=cxp-dev
      ports:
        - "9001:9000"
        - "9098:9099"
    emulator_test_admin:
      container_name: cxp_emulator_test_admin
      image: frfernandezdev/firebase-emulators:latest
      environment:
        - FIREBASE_PROJECT=cxp-dev-admin
      ports:
        - "9099"
    emulator_test_web:
      container_name: cxp_emulator_test_web
      image: frfernandezdev/firebase-emulators:latest
      environment:
        - FIREBASE_PROJECT=cxp-dev
      ports:
        - "9099"
    api:
      build:
        context: .
        dockerfile: ./docker/api/Dockerfile
      env_file: ./docker/api/api.conf
      volumes:
        - ./:/srv/app
      ports:
        - "5000:5000"
      depends_on:
        - db
        - emulator_web
        - emulator_admin
    test:
      build:
        context: .
        dockerfile: ./docker/test/Dockerfile
      env_file: ./docker/test/test.conf
      volumes:
        - ./:/srv/test
      depends_on:
        - db
        - emulator_test_admin
        - emulator_test_web
