version: "3"
services: 
    db: 
        image: postgres:13-alpine
        env_file: db.conf
        ports: 
            - "5432:5432"
    api: 
        build: .
        env_file: api.conf
        volumes: 
            - ./app:/srv/app
        ports:
            - "5000:3000"
        depends_on:
            - db
        restart: always

