version: "3"

services:
    db:
      container_name: cxp_db
      image: postgres:13-alpine
      env_file: ./docker/db/db.conf
      ports:
        - "5432:5432"
      volumes:
        - ./docker/db/pg-init-scripts:/docker-entrypoint-initdb.d
    emulator_admin:
      container_name: cxp_emulator_admin
      image: frfernandezdev/cxp-firebase-ci-admin:latest
      ports:
        - "9000:9000"
        - "9099:9099"
    emulator_web:
      container_name: cxp_emulator_web
      image: frfernandezdev/cxp-firebase-ci-web:latest
      ports:
        - "9001:9001"
        - "9098:9098"
    migrate:
      build:
        context: .
        dockerfile: ./docker/migrate/Dockerfile
      env_file: ./docker/migrate/migrate.conf
      volumes:
        - ./:/srv/app
      depends_on:
        - db
        - emulator_admin
        - emulator_web
    api:
      build:
        context: .
        dockerfile: ./docker/api/Dockerfile
      env_file: ./docker/api/api.conf
      volumes:
        - ./:/srv/app
      ports:
        - "5000:5000"
      depends_on:
        - db
        - emulator_admin
        - emulator_web
    test:
      build:
        context: .
        dockerfile: ./docker/test/Dockerfile
      env_file: ./docker/test/test.conf
      volumes:
        - ./:/srv/test
      depends_on:
        - db
        - emulator_admin
        - emulator_web

networks:
  default:
    driver: bridge
