name: Builder docker image

on:
  push:
    branches:
      - main
        #paths:
        #  - 'src/**.py'
        #  - 'images/Dockerfile'
  pull_request:
    branches:
      - main
        #paths:
        #  - 'src/**.py'
        #- 'images/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
          build-args: |
            SECRET_PASSPHRASE
            FIREBASE_SDK_ADMIN
            FIREBASE_SDK_WEB
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE_DEV }}
          FIREBASE_SDK_ADMIN: cxp-dev-admin-adminsdk.json
          FIREBASE_SDK_WEB: cxp-dev-adminsdk.json
