name: Continuous delivery

on:
  pull_request:
    branches:
      - staging
    tags:
      - v[12].[0-9]+.[0-9]+

jobs:
  staging:
    name: Deploy in staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install dpl
      - name: Deploy in heroku
        run: |
          dpl --provider=heroku --app=cxp-server-staging --api_key=${{secrets.HEROKU_API_KEY}}
