name: Continuous integration

on:
  pull_request:
    branches:
      - main
      - develop
      - staging
      - 'hotfix/**'
      - 'releases/**'
    tags:
      - v[12].[0-9]+.[0-9]+

jobs:
  test:
    name: Testing endpoints
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
      FLASK_ENV: "development"
      FLASK_DEBUG: "True"
      TESTING: "True"
      FIREBASE_AUTH_EMULATOR_ADMIN_HOST: "localhost:9099"
      FIREBASE_AUTH_EMULATOR_WEB_HOST: "localhost:9098"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      emulator_admin:
        image: frfernandezdev/firebase-emulators
        env:
          FIREBASE_PROJECT: conexperto-admin
        ports:
          - 9099:9099
      emulator_web:
        image: frfernandezdev/firebase-emulators
        env:
          FIREBASE_PROJECT: conexperto-6b5e7
        ports:
          - 9098:9099
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Run testing
        run: |
          pytest --junitxml=report.xml
