name: Code Quality


on: [push]

jobs:
  code_quaity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Run black
        run: |
          black --check --diff --config=.black

      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics
