name: Continuous Deployment

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cxp-server-prod"
          heroku_email: "conexpertoteam@gmail.com"
          usedocker: true
          docker_build_args: |
            SECRET_PASSPHRASE
            FIREBASE_SDK_ADMIN
            FIREBASE_SDK_WEB
          branch: "staging"
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
          FIREBASE_SDK_ADMIN: conexperto-admin-adminsdk.json
          FIREBASE_SDK_WEB: conexperto-admin-adminsdk.json
