name: Continuous Deployment

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Install dpl
        run: |
           gem install dpl
      - name: Deployment on Heroku
        run: |
           dpl --provider=heroku --app=cxp-server-prod --api_key=${{ secrets.HEROKU_API_KEY }}
