name: CI/CD

on: 
  push: 
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  format: 
    name: Formatting Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        options: "--config .black --check --diff"
        version: "21.5b1"
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Link with flake8
        run: |
          flake8 . --count --show-source --statistics
